plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'me.modmuss50.mod-publish-plugin' version '1.1.0'
}

version = "${mod_version}${fabricVersionAppend}"
group = project.maven_group

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = 'Modrinth'
				url = 'https://api.modrinth.com/maven'
			}
		}
		filter {
			includeGroup 'maven.modrinth'
		}
	}
	maven {
		name = 'CurseMaven'
		url = 'https://www.cursemaven.com'
	}
	maven {
		name = 'Fuzs Mod Resources'
		url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	implementation "maven.modrinth:dynamictrees:${dynamicTreesVersion}"
	implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forgeConfigApiPortVersion}"
	runtimeOnly "maven.modrinth:dynamictreesplus:${dynamicTreesPlusVersion}"
	runtimeOnly "maven.modrinth:terralith:${terralithVersion}"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

processResources {
	def version = project.version
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand 'version': version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from('LICENSE') {
		rename { "${it}_${project.archivesBaseName}" }
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			url 'file://' + project.projectDir + '/repo'
		}
		var mavenUsername = project.findProperty('harleyOConnorMavenUsername')?.toString() ?: System.getenv('MAVEN_USERNAME')
		var mavenPassword = project.findProperty('harleyOConnorMavenPassword')?.toString() ?: System.getenv('MAVEN_PASSWORD')
		if (mavenUsername != null && mavenPassword != null) {
			maven {
				name = 'HarleyOConnor'
				url = 'https://harleyoconnor.com/maven'
				credentials {
					username = mavenUsername
					password = mavenPassword
				}
			}
		}
	}
}

def changelogFile = file('build/changelog.txt')

publishMods {
	file = jar.archiveFile
	displayName = "${mod_name.replace(' ', '')}-Fabric-${minecraft_version} ${version}"
	if (changelogFile.exists()) {
		changelog.set(changelogFile.getText())
	}
	type = me.modmuss50.mpp.ReleaseType.of(versionType.toUpperCase())
	modLoaders.add('fabric')

	curseforge {
		projectId = '852886'
		projectSlug = 'dynamic-trees-terralith'
		accessToken = project.findProperty('curseApiKey') ?: System.getenv('CURSEFORGE_API_KEY')
		minecraftVersions.add('26.1')
		requires('dynamictrees')
		requires('terralith')
		optional('dynamictreesplus')
	}
	modrinth {
		projectId = 'o8eM9Cnp'
		accessToken = project.findProperty('modrinthToken') ?: System.getenv('MODRINTH_TOKEN')
		minecraftVersions.add('26.1')
		requires('vdjF5PL5')
		requires('8oi3bsk5')
		optional('qaO9Dqpu')
	}
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}
